<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-07T07:04:36 IST" name="Default suite" finished-at="2021-03-07T07:04:46 IST" duration-ms="9812">
    <groups>
    </groups>
    <test started-at="2021-03-07T07:04:36 IST" name="Default test" finished-at="2021-03-07T07:04:46 IST" duration-ms="9812">
      <class name="datadriventesting.DataDrivenTest_AddnewEmployee">
        <test-method signature="postNewEmployees(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:datadriventesting.DataDrivenTest_AddnewEmployee@51f116b8]" started-at="2021-03-07T07:04:39 IST" name="postNewEmployees" data-provider="empdataprovider" finished-at="2021-03-07T07:04:43 IST" duration-ms="4606" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[sam345]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[35000]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[27]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postNewEmployees -->
        <test-method signature="postNewEmployees(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:datadriventesting.DataDrivenTest_AddnewEmployee@51f116b8]" started-at="2021-03-07T07:04:43 IST" name="postNewEmployees" data-provider="empdataprovider" finished-at="2021-03-07T07:04:44 IST" duration-ms="1015" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Basha123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[50000]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[28]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at datadriventesting.DataDrivenTest_AddnewEmployee.postNewEmployees(DataDrivenTest_AddnewEmployee.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postNewEmployees -->
        <test-method signature="postNewEmployees(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:datadriventesting.DataDrivenTest_AddnewEmployee@51f116b8]" started-at="2021-03-07T07:04:44 IST" name="postNewEmployees" data-provider="empdataprovider" finished-at="2021-03-07T07:04:45 IST" duration-ms="950" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Praveen123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[70000]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[29]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postNewEmployees -->
        <test-method signature="postNewEmployees(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:datadriventesting.DataDrivenTest_AddnewEmployee@51f116b8]" started-at="2021-03-07T07:04:45 IST" name="postNewEmployees" data-provider="empdataprovider" finished-at="2021-03-07T07:04:46 IST" duration-ms="976" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Bala123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[80000]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at datadriventesting.DataDrivenTest_AddnewEmployee.postNewEmployees(DataDrivenTest_AddnewEmployee.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postNewEmployees -->
      </class> <!-- datadriventesting.DataDrivenTest_AddnewEmployee -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
